stages:

  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - data/processed/train_features.csv
      - data/processed/test_features.csv